# Generated by Django 5.0.6 on 2024-08-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moria', '0002_profile_birth_date_profile_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
