# Generated by Django 5.0.6 on 2024-08-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moria', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
